---

   - name: Install package updates on CentOS hosts
     yum:
       name=*
       state=latest
       update_cache=yes
     when: ansible_distribution == "CentOS"


   - name: Install package updates on Ubuntu hosts
     apt:
       upgrade=dist
       update_cache=yes
     when: ansible_distribution == "Ubuntu"
