---

   - name: Create technical user on Centos hosts
     user:
        name: technical
        password: '$6$rvwfqIq3PjD4y7d$yAUUaik.HtROOXCcNQgJTiP42p1lZQZcwMIpzj7NCtrWMZCj87WxN2kIn4UKH0V0FCD2npSHRA83e0StPJyd0.'
        groups: wheel
        state: present
        shell: /bin/bash       # Defaults to /bin/bash
        system: no             # Defaults to no
        createhome: yes        # Defaults to yes
        home: /home/technical  # Defaults to /home/<username>
     when: ansible_distribution == "CentOS"
     
   - name: Create technical user on Ubuntu hosts
     user:
        name: technical
        password: '$6$rvwfqIq3PjD4y7d$yAUUaik.HtROOXCcNQgJTiP42p1lZQZcwMIpzj7NCtrWMZCj87WxN2kIn4UKH0V0FCD2npSHRA83e0StPJyd0.'
        groups: sudo
        state: present
        shell: /bin/bash       # Defaults to /bin/bash
        system: no             # Defaults to no
        createhome: yes        # Defaults to yes
        home: /home/technical  # Defaults to /home/<username>
     when: ansible_distribution == "Ubuntu"

   - name: Add technical user to the sudoers - Centos
     lineinfile:    
        path: /etc/sudoers
        line: "technical  ALL=(ALL)  NOPASSWD: ALL"
     when: ansible_distribution == "CentOS"


   - name: Add technical user to the sudoers - Ubuntu
     lineinfile:
        path: /etc/sudoers.d/technical
        line: "technical  ALL=(ALL)  NOPASSWD: ALL"
     when: ansible_distribution == "Ubuntu"

