---

   - name: Install Docker dependencies on Centos
     become: yes                                 #allows to use sudo when installing as non-root user
     yum:
       name: [yum-utils, device-mapper-persistent-data,lvm2]
       state: present
     when: ansible_distribution == "CentOS"

   - name: Install Docker packages on Centos
     become: yes                                 #allows to use sudo when installing as non-root user
     yum:
       name: [docker-ce]
       state: present
     when: ansible_distribution == "CentOS"


   - name: Install Docker packages on Ubuntu
     become: yes                                 #allows to use sudo when installing as non-root user
     apt:
       name: [docker-ce]
       state: present
     when: ansible_distribution == "Ubuntu"


   - name: Starting and Enabling the Docker service - CentOS
     service:
       name: docker
       state: started
       enabled: yes
