---

   - name: Install Docker dependencies
     become: yes                                 #allows to use sudo when installing as non-root user
     yum:
       name: [yum-utils, device-mapper-persistent-data,lvm2]
       state: present
     when: ansible_distribution == "CentOS"

   - name: Install Docker packages
     become: yes                                 #allows to use sudo when installing as non-root user
     yum:
       name: [docker-ce]
       state: present
     when: ansible_distribution == "CentOS"

