---

   - name: Install kubernetes-cni packages
     become: yes                                 #allows to use sudo when installing as non-root user
     yum:
       name: kubernetes-cni-0.6.0
       state: present
     when: ansible_distribution == "CentOS"


   - name: Install Kubernetes packages on CentOS
     become: yes                                 #allows to use sudo when installing as non-root user
     yum:
       name: [kubectl,kubelet,kubeadm]
       state: present
     when: ansible_distribution == "CentOS"


   - name: Install Kubernetes packages on Ubuntu
     become: yes                                 #allows to use sudo when installing as non-root user
     apt:
       name: [kubectl,kubelet,kubeadm]
       state: present
     when: ansible_distribution == "Ubuntu"

   - name: Reload systemd deamon
     command: systemctl daemon-reload


   - name: Starting and Enabling the Kubelet service 
     service:
       name: kubelet.service
       state: started
       enabled: yes
#     when: ansible_distribution == "CentOS"

