---

   - name: Install kubernetes-cni on master Centos
     become: yes                                 #allows to use sudo when installing as non-root user
     yum:
       name: kubernetes-cni-0.6.0
       state: present
     when: ansible_distribution == "CentOS" and ansible.hostname == "{{ kubernetes_master }}"


   - name: Install main Kubernetes packages if master CentOS
     become: yes                                 #allows to use sudo when installing as non-root user
     yum:
       name: [kubectl,kubeadm]
       state: present
     when: ansible_distribution == "CentOS" and ansible.hostname == "{{ kubernetes_master }}"
     

   - name: Install main Kubernetes packages if master Ubuntu
     become: yes                                 #allows to use sudo when installing as non-root user
     apt:
       name: [kubectl,kubeadm]
       state: present
     when: ansible_distribution == "Ubuntu" and ansible.hostname == "{{ kubernetes_master }}"
     

   - name: Install Kubernetes agent on node Centos
     become: yes                                 #allows to use sudo when installing as non-root user
     yum:
       name: [kubelet]
       state: present
     when: ansible_distribution == "CentOS" and ansible.hostname != "{{ kubernetes_master }}"

  
   - name: Install Kubernetes agent on node Ubuntu
     become: yes                                 #allows to use sudo when installing as non-root user
     apt:
       name: [kubelet]
       state: present
     when: ansible_distribution == "Ubuntu" ans ansible.hostname != "{{ kubernetes_master }}"


   - name: Reload systemd deamon
     command: systemctl daemon-reload


   - name: Starting and Enabling the Kubelet service 
     service:
       name: kubelet.service
       state: started
       enabled: yes
