---

   - name: Install Kubernetes packages
     become: yes                                 #allows to use sudo when installing as non-root user
     yum:
       name: [kubectl,kubeadm, docker-ce]
       state: present


#   - name: Starting and Enabling the Docker service - CentOS
#     service:
#       name: kubectl
#       state: started
#       enabled: yes
