---

   - name: Install Kubernetes packages on CentOs
     become: yes                                 #allows to use sudo when installing as non-root user
     yum:
       name: [kubectl,kubeadm]
       state: present
     when: ansible_distribution == "CentOS"


   - name: Install Kubernetes packages on Ubuntu
     become: yes                                 #allows to use sudo when installing as non-root user
     yum:
       name: [kubectl,kubeadm]
       state: present
     when: ansible_distribution == "Ubuntu"


   - name: Restart and Enable the Kubelet service - Ubuntu
     service:
       name: kubelet
       state: restarted
       enabled: yes
