---

   - name: Install Kubernetes packages
     become: yes                                 #allows to use sudo when installing as non-root user
     yum:
       name: [kubectl,kubeadm, docker-ce]
       state: present
