---

   - name: Install Ansible packages
     become: yes                                 #allows to use sudo when installing as non-root user
     yum:
       name: ansible
       state: present
     when: ansible_distribution == "CentOS"

   - name: Install Docker packages on Ubuntu hosts
     become: yes                                 #allows to use sudo when installing as non-root user
     apt:
       name: ansible
       state: present
     when: ansible_distribution == "Ubuntu"


#   - name: Starting and Enabling the Docker service - CentOS
#     service:
#       name: kubectl
#       state: started
#       enabled: yes
