---

   - name: Install Ansible packages on CentOS
     become: yes                                 #allows to use sudo when installing as non-root user
     yum:
       name: ansible
       state: present
     when: ansible_distribution == "CentOS"

   - name: Install Ansible packages on Ubuntu hosts
     become: yes                                 #allows to use sudo when installing as non-root user
     apt:
       name: ansible
       state: present
     when: ansible_distribution == "Ubuntu"
