---
   - name: Add kubernetes repository in CentOS hosts
     yum_repository:
      name: kubernetes_repo
      description: Kubernetes
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled: yes
      gpgcheck: yes
      repo_gpgcheck: yes
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
     when: ansible_distribution == "CentOS" 
     


   - name: Add Kubernetes apt-key to repository on Ubuntu
     apt_key:
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present
     when: ansible_distribution == "Ubuntu"


   - name: Add Kubernetes repository on Ubuntu
     apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: 'kubernetes' 
     when: ansible_distribution == "Ubuntu"



#***********************
#DOCKER
#***********************

   - name: Add Docker repository on CentOS
     shell: |
       yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
     when: ansible_distribution == "CentOS"

   - name: Add Docker apt-key to repository on Ubuntu
     apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
     when: ansible_distribution == "Ubuntu"

   - name: Add Docker repository on Ubuntu
     apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
     when: ansible_distribution == "Ubuntu"
