---
      
   - name: Update /etc/hosts file
     become: yes
     become_user: root
     copy:
       content: "{{ host_file }}"
       dest: /etc/hosts
    
   - name: Update aliases
     blockinfile:
       path: /{{ ansible_user_dir }}/.bashrc
       block:  |
          # custom aliases
          alias kube-01="ssh root@51.161.8.73"
          alias master_a="ssh root@54.38.189.194"
          alias master_j="ssh root@167.114.2.104"
       insertafter: EOF

   - name: Reload .bashrc file
     file:
       path: /{{ ansible_user_dir }}/.bashrc
       state: touch



