---
  - name: Check docker is running
    shell: systemctl status docker | head -n 3 | tail -n 1 | awk '{ print $2 $3 }'
#    command: systemctl status docker
    register: docker_status

  - debug: 
      msg:  "{{ docker_status.stdout }}"
